services:
  dbservice:
    image: mysql:latest
    container_name: jobportaldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - C:/Users/91966/Desktop/jobportal-data:/var/lib/mysql